name: Release CI

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # 👈 Adicione esta linha
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
      - run: npm install
      - run: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GENERATE }}
